import test from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import os from 'node:os';
import path from 'node:path';
import { serviceFixture } from './runtime-fixture.mjs';
const { chromium } = createRequire(import.meta.url)(process.env.DAGUAN_PLAYWRIGHT_MODULE || 'playwright');

test('学习手账：真实足迹、印章、题干安全、主题、跨窗口与读取失败保护', { timeout: 60000 }, async t => {
  const { base } = await serviceFixture(t);
  const browser = await chromium.launch({ ...(process.env.DAGUAN_CHROMIUM_EXECUTABLE ? { executablePath: process.env.DAGUAN_CHROMIUM_EXECUTABLE } : {}) });
  t.after(() => browser.close());
  const context = await browser.newContext({ viewport: { width: 1360, height: 1000 }, timezoneId: 'Asia/Hong_Kong', serviceWorkers: 'block' });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base + '/index.html?ui=new');
  await page.waitForFunction(() => window.AppState?.categories && window.StateSync?.hydrated && document.querySelector('.subject-grid'));
  const ids = await page.evaluate(() => Object.keys(AppState.idIndex).filter(id => App.historyLocation(id)).slice(0, 52));
  assert.equal(ids.length, 52);
  const at = new Date(Date.now() - 5000).toISOString(), yesterday = new Date(Date.now() - 86400000).toISOString();
  const e = (id, time, extra = {}) => ({ event_id: crypto.randomUUID(), question_id: id, at: time, type: 'study', chapter_name: '积分计算', ...extra });
  const events = [e(ids[0], yesterday, { type: 'answer', correct: false, reliable: true }), ...ids.slice(0, 50).map(id => e(id, at)),
    e(ids[0], at, { type: 'answer', correct: true, reliable: true }), e(ids[0], at, { type: 'answer', correct: true, reliable: true })];
  const response = await fetch(base + '/api/study-activity/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ events }) });
  assert.equal(response.status, 200);
  await page.locator('[data-view="records"]').click();
  await page.waitForFunction(() => document.querySelector('.journal-metrics strong')?.textContent === '50');
  assert.equal(await page.locator('.journal-day').count(), 7);
  assert.deepEqual(await page.locator('.journal-metrics strong').allTextContents(), ['50', '49', '1']);
  assert.match(await page.locator('.journal-story-copy').textContent(), /1 道旧错题/);
  await page.locator('.journal-log > summary').first().click();
  await page.waitForFunction(() => document.querySelectorAll('.journal-question').length === 30);
  assert.equal(await page.locator('.journal-question').count(), 30);
  await page.getByRole('button', { name: '显示更多题目', exact: true }).click();
  assert.equal(await page.locator('.journal-question').count(), 50);
  await page.evaluate(() => { DataService.getQuestion = async () => ({ stem: '<img src=x onerror="window.journalInjected=1"><button data-app-action="show-home" onclick="window.journalInjected=1">伪造动作</button> $x^2$' }); });
  await page.locator('.journal-preview > summary').first().click();
  await page.waitForSelector('.journal-stem .katex');
  assert.equal(await page.locator('.journal-stem [onclick], .journal-stem [onerror], .journal-stem [data-app-action]').count(), 0);
  assert.equal(await page.evaluate(() => window.journalInjected), undefined);
  await page.getByRole('button', { name: '回到这题', exact: true }).first().click();
  await page.waitForFunction(() => AppState.currentView === 'question' && !!document.querySelector('.question-stem'));
  await page.locator('[data-view="records"]').click();
  await page.waitForSelector('.journal-day');
  await page.getByRole('tab', { name: '成长印章' }).click();
  assert.equal(await page.locator('.journal-badges .earned').count(), 3);
  assert.match(await page.locator('.journal-badges .earned').allTextContents().then(a => a.join('')), /积少成多/);
  await page.getByRole('tab', { name: '成长印章' }).press('ArrowLeft');
  assert.equal(await page.getByRole('tab', { name: '我的学习手账' }).getAttribute('aria-selected'), 'true');
  await page.locator('.journal-day').first().click();
  assert.equal(await page.locator('.journal-metrics strong').first().textContent(), '0');
  await page.locator('[data-journal-today]').click();
  await page.waitForFunction(() => document.querySelector('.journal-metrics strong')?.textContent === '50');
  for (const appearance of ['path-red', 'orange-white', 'blue-sand', 'eye-care', 'orange-night', 'mint'].map(theme => ({ theme })).concat({ theme: 'path-red', brand: '#835E3D', reading: '#FCF8EF', app: '#F3EBDE' })) {
    await page.evaluate(appearance => applyAppearanceValues(appearance), appearance);
    assert.equal(await page.locator('.journal-day[aria-pressed=true]').evaluate(el => getComputedStyle(el).backgroundColor),
      await page.evaluate(() => { const el = document.createElement('span'); el.style.backgroundColor = 'var(--brand-light-bg)'; document.body.append(el); const value = getComputedStyle(el).backgroundColor; el.remove(); return value; }));
    assert.equal(await page.locator('.journal-layout').evaluate(el => getComputedStyle(el).backgroundColor),
      await page.evaluate(() => { const el = document.createElement('span'); el.style.backgroundColor = 'var(--bg-surface)'; document.body.append(el); const value = getComputedStyle(el).backgroundColor; el.remove(); return value; }));
  }
  await page.evaluate(() => applyAppearanceValues({ theme: 'path-red' }));
  await page.screenshot({ path: path.join(os.tmpdir(), 'study-journal-desktop.png'), animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => document.documentElement.style.setProperty('--ui-font-scale', '1.5'));
  assert.ok(await page.locator('.study-journal').evaluate(el => el.scrollWidth <= el.clientWidth));
  await page.screenshot({ path: path.join(os.tmpdir(), 'study-journal-mobile.png'), animations: 'disabled' });
  await page.setViewportSize({ width: 1360, height: 1000 });
  await page.evaluate(() => document.documentElement.style.setProperty('--ui-font-scale', '1'));
  const second = await context.newPage();
  await second.goto(base + '/index.html?ui=new');
  await second.waitForFunction(() => window.DaguanStudyActivity && window.StateSync?.hydrated);
  await second.evaluate(async id => { DaguanStudyActivity.study(id, { chapter_name: '线性代数' }); await DaguanStudyActivity.flush(); }, ids[50]);
  await page.waitForFunction(() => document.querySelector('.journal-metrics strong')?.textContent === '51');
  // Unchanged notifications preserve expanded details and keyboard focus.
  if (!(await page.locator('.journal-log').first().evaluate(el => el.open))) await page.locator('.journal-log > summary').first().click();
  await page.locator('.journal-log > summary').first().focus();
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('daguan:study-activity')));
  await page.waitForFunction(() => document.querySelector('.study-journal')?.getAttribute('aria-busy') === 'false');
  assert.equal(await page.locator('.journal-log').first().getAttribute('open'), '');
  assert.ok(await page.locator('.journal-log > summary').first().evaluate(el => el === document.activeElement));
  await context.route('**/api/study-activity/journal?*', r => r.fulfill({ status: 500, body: '{}' }));
  await page.locator('[data-journal-refresh]').click();
  await page.waitForFunction(() => document.querySelector('.journal-status')?.textContent.includes('读取失败'));
  assert.equal(await page.locator('.journal-metrics strong').first().textContent(), '51');
  await context.unroute('**/api/study-activity/journal?*');
  await page.locator('[data-journal-refresh]').click();
  await page.waitForFunction(() => document.querySelector('.study-journal')?.getAttribute('aria-busy') === 'false');
  // Pending edits survive failed reads and a reload, then reconcile into real records.
  await context.route('**/api/study-activity/events', r => r.abort());
  await second.evaluate(id => DaguanStudyActivity.study(id, { chapter_name: '<img src=x onerror="window.journalInjected=1">' }), ids[51]);
  await second.waitForFunction(() => DaguanStudyActivity.pendingCount() > 0);
  await second.reload();
  await second.waitForFunction(() => window.StateSync?.hydrated);
  assert.ok(await second.evaluate(() => DaguanStudyActivity.pendingCount() > 0));
  await context.unroute('**/api/study-activity/events');
  await second.evaluate(async () => { await DaguanStudyActivity.flush(); await DaguanStudyActivity.flush(); });
  await page.waitForFunction(() => document.querySelector('.journal-metrics strong')?.textContent === '52');
  assert.equal(await page.locator('.journal-log > summary img').count(), 0);
  await page.reload();
  await page.waitForFunction(() => window.StateSync?.hydrated && document.querySelector('.subject-grid'));
  await page.locator('[data-view="records"]').click();
  await page.waitForFunction(() => document.querySelector('.journal-metrics strong')?.textContent === '52');
  await page.locator('[data-journal-history]').click();
  await page.waitForSelector('#history-results');
  assert.deepEqual(errors, []);
});

test('空手账与日期回看：不伪造旧记录，跨周和自选日期正确切换', { timeout: 30000 }, async t => {
  const { base } = await serviceFixture(t);
  const browser = await chromium.launch({ ...(process.env.DAGUAN_CHROMIUM_EXECUTABLE ? { executablePath: process.env.DAGUAN_CHROMIUM_EXECUTABLE } : {}) });
  t.after(() => browser.close());
  const page = await browser.newPage({ timezoneId: 'Asia/Hong_Kong', serviceWorkers: 'block' });
  await page.goto(base + '/index.html?ui=new');
  await page.waitForFunction(() => window.StateSync?.hydrated && document.querySelector('.subject-grid'));
  await page.locator('[data-view="records"]').click();
  await page.waitForSelector('.journal-empty');
  assert.deepEqual(await page.locator('.journal-metrics strong').allTextContents(), ['0', '0', '0']);
  assert.equal(await page.locator('.journal-badges .earned').count(), 0);
  assert.ok(await page.locator('[data-journal-prev]').isDisabled());
  const now = new Date(), past = new Date(now.getTime() - 86400000 * 15).toISOString();
  await fetch(base + '/api/study-activity/events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ events: [{ event_id: crypto.randomUUID(), question_id: '129', at: past, type: 'study', chapter_name: '旧日练习' }] }) });
  await page.waitForFunction(() => !document.querySelector('[data-journal-prev]').disabled);
  await page.locator('[data-journal-prev]').click();
  await page.waitForFunction(() => document.querySelector('.study-journal').getAttribute('aria-busy') === 'false');
  await page.locator('[data-journal-prev]').click();
  await page.waitForFunction(() => document.querySelector('.journal-day small') && [...document.querySelectorAll('.journal-day small')].some(el => el.textContent === '1 题'));
  await page.locator('.journal-day', { hasText: '1 题' }).click();
  assert.equal(await page.locator('.journal-metrics strong').first().textContent(), '1');
  const oldDay = await page.locator('[data-journal-date]').inputValue();
  await page.locator('[data-journal-today]').click();
  await page.waitForFunction(() => document.querySelector('[data-journal-next]').disabled);
  await page.locator('[data-journal-date]').fill(oldDay);
  await page.locator('[data-journal-date]').dispatchEvent('change');
  await page.waitForFunction(() => document.querySelector('.journal-metrics strong')?.textContent === '1');
  assert.equal(await page.locator('[data-journal-date]').inputValue(), oldDay);
  await page.getByRole('tab', { name: '成长印章' }).click();
  assert.equal(await page.locator('.journal-badges .earned').count(), 1);
});
