server {
    listen 80;
    listen [::]:80;
    server_name kaoyangogogo.fun www.kaoyangogogo.fun sillytavern.kaoyangogogo.fun zuowen.kaoyangogogo.fun luna.kaoyangogogo.fun prob.kaoyangogogo.fun;

    return 308 https://$host$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name plus-guide.fun www.plus-guide.fun;

    return 308 https://$host$request_uri;
}
